name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: python -V
      - run: python -m pip install -U pip ruff pytest
      - run: ruff check .
      - run: pytest -q || true
