name: CI

on:
  push:
    branches: [ main, feat/** ]
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "15 2 * * *"  # runs at 02:15 UTC nightly

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install -r requirements.lock.txt || true
          pip install -e .
          pip install pytest matplotlib
      - name: Smoke tests
        run: |
          pytest -q
      - name: Build artifacts (no external keys)
        run: |
          python -m features.build_features --config config/pipeline.yaml || true
          python -m backtests.model_backtest -r 0.0001 || true
          python -m backtests.qwalk_backtest --mix 0.45 --df 4 --paths 2000 || true
          python -m backtests.calibrate || true
          python -m backtests.compare || true
          python -m backtests.coverage || true
          python -m backtests.plots || true
          python -m backtests.make_report || true
      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            reports/**
            preds/**
            data/proc/features.parquet
          if-no-files-found: warn
